// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/signin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "SignIn",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "SignIn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "csrf token",
                        "name": "x-csrf-token",
                        "in": "header"
                    },
                    {
                        "description": "SignIn user",
                        "name": "signin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqres.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/average-performance-score-per-department": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Average Performance Score Per Department with Employee Count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PerformanceAnalysis"
                ],
                "summary": "Get Dashboard Average Performance Score Per Department with Count",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-average-emp-satisfaction-per-position": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Average Employee Satisfaction Per Position",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PerformanceAnalysis"
                ],
                "summary": "Get Dashboard Bar Chart Average Employee Satisfaction Per Position",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-average-salary-per-department": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get SalaryDistribution Bar Chart Average Salary Per Department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SalaryDistribution"
                ],
                "summary": "Get SalaryDistribution Bar Chart Average Salary Per Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-average-salary-per-position": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get SalaryDistribution Bar Chart Average Salary Per Position with Employee Count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SalaryDistribution"
                ],
                "summary": "Get SalaryDistribution Bar Chart Average Salary Per Position with Employee Count",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-per-citizen-desc": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Per Citizen Description",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Bar Chart Per Citizen Description",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-per-department": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Per Department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Bar Chart Per Department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "gender (string) (m/f)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-per-gender": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Per Department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Bar Chart Per Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-per-race-desc": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Per Race Description",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Bar Chart Per Race Description",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-per-recruitment-source": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Per Recruitment Source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Bar Chart Per Recruitment Source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-termination-by-department": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Employee Termination By Department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TerminationAnalysis"
                ],
                "summary": "Get Dashboard Bar Chart Employee Termination By Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/barchart-employee-termination-by-reason": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Bar Chart Employee Termination By Reason",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TerminationAnalysis"
                ],
                "summary": "Get Dashboard Bar Chart Employee Termination By Reason",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/highest-lowest-salary": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Highest and Lowest Salary",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SalaryDistribution"
                ],
                "summary": "Get Dashboard Highest and Lowest Salary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/linechart-late-absence-trend": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Line Chart Late/Absence Trend per Month/Year",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Line Chart Late/Absence Trend",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "month",
                        "description": "period_type (month/year)",
                        "name": "period_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "both",
                        "description": "trend_type (late/absence/both)",
                        "name": "trend_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/linechart-performance-trend": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Line Chart Average Performance Score Trend per Month/Year",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Line Chart Performance Score Trend",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "month",
                        "description": "period_type (month/year)",
                        "name": "period_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/linechart-recruitment-trend": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Line Chart Recruitment Trend per Month/Year",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Line Chart Recruitment Trend",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "month",
                        "description": "period_type (month/year)",
                        "name": "period_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/linechart-turnover-trend": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Line Chart Turnover Trend per Month/Year",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Line Chart Turnover Trend",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "month",
                        "description": "period_type (month/year)",
                        "name": "period_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/piechart-employee-termination-ratio": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Pie Chart Employee Termination Ratio (Voluntarily vs Terminated for Cause)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TerminationAnalysis"
                ],
                "summary": "Get Dashboard Pie Chart Employee Termination Ratio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dashboard/score-card": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get Dashboard Score Card",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Dashboard Score Card",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department_id (int)",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender (string) (m/f)",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "state (string)",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "emp_status_id (int)",
                        "name": "emp_status_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "position_id (int)",
                        "name": "position_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "manager_id (int)",
                        "name": "manager_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date (format: 2006-01-02)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_date (format: 2006-01-02)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/department": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Department With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Department With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: id)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "created_at_margin_top (format: 2006-01-02)",
                        "name": "created_at_margin_top",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "created_at_margin_top (format: 2006-01-02)",
                        "name": "created_at_margin_bottom",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/employee": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Employees With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Employees With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: EmpID)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/employment-status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Employment Statuses With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Employment Statuses With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: EmpStatusID)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/manager": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Managers With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Managers With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: ManagerID)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/marital-status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Marital Statuses With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Marital Statuses With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: MaritalStatusID)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/performance": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Performance Scores With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Performance Scores With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: PerfScoreID)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/dim/position": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "JwtToken": []
                    }
                ],
                "description": "Get All Positions With Pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dim Table"
                ],
                "summary": "Get All Positions With Pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search (string)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (int)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit (int)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort (ASC/DESC)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order by (default: PositionID)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/version": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get Version Build",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Home"
                ],
                "summary": "Get Version Build",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "reqres.SignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JwtToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "V1.2412.081710",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "HRIS Data Warehouse",
	Description:      "API documentation by Kang Fakhrur",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
